# Generated by Django 4.2.18 on 2025-01-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idChat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('horasTotales', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Checadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.TimeField()),
                ('fechaEntrada', models.CharField(max_length=20)),
                ('horaSalida', models.TimeField(blank=True, null=True)),
                ('fechaSalida', models.CharField(blank=True, max_length=20, null=True)),
                ('horas', models.TimeField(blank=True, null=True)),
                ('identificador', models.ForeignKey(db_column='identificador', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.alumno')),
            ],
            options={
                'db_table': 'checadas',
            },
        ),
    ]
